try{
    let a = 0;
    console.log(program);
    console.log(" Program ran Successfully");
}
catch (err){
    console.log("This is an error");
}
finally{
    console.log("I am a good boy")
}